#pragma once

#ifdef _WIN32
#define LUVLETTER_NATIVE_CALL __stdcall
#define LUVLETTER_NATIVE_EXPORT __declspec(dllexport)
#else
#define LUVLETTER_NATIVE_CALL
#define LUVLETTER_NATIVE_EXPORT
#endif

extern "C"
{
	LUVLETTER_NATIVE_EXPORT int LUVLETTER_NATIVE_CALL ShowInputBox();
	LUVLETTER_NATIVE_EXPORT int LUVLETTER_NATIVE_CALL HideInputBox();
	LUVLETTER_NATIVE_EXPORT int LUVLETTER_NATIVE_CALL ToggleInputBox();
	LUVLETTER_NATIVE_EXPORT void LUVLETTER_NATIVE_CALL ShutdownInputBox();
}
